version: 2.1

references:
  working_dir: &working_dir /tmp/workspace/farmsmart

  workspace: &workspace /tmp/workspace

  gcp-firebase_dir: &gcp-firebase_dir /tmp/workspace/farmsmart/gcp-firebase

  gcp-firebase-emulator_dir: &gcp-firebase-emulator_dir /tmp/workspace/farmsmart/gcp-firebase-emulator

  utilities_dir: &utilities_dir /tmp/workspace/farmsmart/utilities

  restore_workspace: &restore_workspace
    attach_workspace:
      at: *workspace

  save_workspace: &save_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - farmsmart

  login_to_docker_hub: &login_to_docker_hub
    run:
          name: Login to docker hub
          command: |
            set -euo pipefail
            docker login -u $DOCKER_USER -p $DOCKER_PASS
  
  build_and_push_to_docker_hub: &build_and_push_to_docker_hub
    run:
          name: Build docker image
          command: |
            set -euo pipefail
            export tagversion=$CIRCLE_TAG
            docker build -t $REPO -t $REPO:${tagversion} .
            docker push $REPO

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: *working_dir  
    steps:
      - checkout
      - *save_workspace

  utilities:
    machine: true
    working_directory: *utilities_dir
    environment:
      REPO: farmsmart/utilities
    steps:
      - *restore_workspace
      - *login_to_docker_hub
      - *build_and_push_to_docker_hub
 
  gcp-firebase:
    machine: true
    working_directory: *gcp-firebase_dir
    environment:
      REPO: farmsmart/gcp-firebase
    steps:
      - *restore_workspace
      - *login_to_docker_hub
      - *build_and_push_to_docker_hub
  
  gcp-firebase-emulator:
    machine: true
    working_directory: *gcp-firebase-emulator_dir
    environment:
      REPO: farmsmart/gcp-firebase-emulator
    steps:
      - *restore_workspace
      - *login_to_docker_hub
      - *build_and_push_to_docker_hub

workflows:
  farmsmart-image:
    jobs:
      - build

      - utilities:
          name: utilities
          requires:
            - build
          context: docker-hub
          filters:
            branches:
              only: master
            tag:
              only: /^v.*/

      - gcp-firebase:
          requires:
            - build
          context: docker-hub
          filters:
            branches:
              only: master
            tag:
              only: /^v.*/

      - gcp-firebase-emulator:
          name: emulator-dependency
          requires:
            - gcp-firebase
          context: docker-hub
          filters:
            branches:
              only: master
            tag:
              only: /^v.*/

      
